"""Versioned constants ported from AIHOT 035f7b7 (MIT). Changing them changes rankings."""

from leaderboard.method.types import Policy, ScoringSource

METHOD_VERSION = "2026.09-public-consensus-v15"
SCORE_DEFINITION = (
    "Cumulative Kemeny ordering support relative to fixed anchors; "
    "not capability distance or calibrated win probability"
)
DISPLAY_METHOD = "kemeny-order-support-1.0"
CARRY_FORWARD_DAYS = 7
CONFIGURATION_POLICY = "representative-config-v13"
RELEASE_WINDOW_MONTHS = 18
CATEGORY_MIN_MODELS = 5
BOARD_KEYS = (
    "overall",
    "coding",
    "aesthetics",
    "reasoning",
    "knowledge",
    "writing",
    "professional",
)
OVERALL_POLICY = Policy(3, 3, 3, 3, 2)
BUDGETS = (
    ("broad", "综合评测", 0.30),
    ("preference", "真人盲选", 0.10),
    ("coding", "编程与设计", 0.12),
    ("writing", "写作与表达", 0.09),
    ("reasoning", "数学与推理", 0.12),
    ("knowledge", "知识与事实", 0.06),
    ("vision", "视觉理解", 0.06),
    ("tools", "工具与办公", 0.06),
    ("multilingual", "中文与多语言", 0.06),
    ("professional", "行业专业任务", 0.03),
)
SCORING_SOURCES = (
    ScoringSource(
        "artificial-analysis",
        "artificial-analysis:intelligence",
        0.3,
        "broad-composite",
        "artificial-analysis",
        "broad",
        None,
        True,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "artificial-analysis-multilingual",
        "artificial-analysis-multilingual",
        0.06,
        "multilingual",
        "artificial-analysis",
        "multilingual",
        None,
        False,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "arena-text",
        "arena-text",
        0.05,
        "arena-preference",
        "arena",
        "preference",
        None,
        True,
        1.96,
        "HIGHER",
    ),
    ScoringSource(
        "arena-webdev",
        "arena-webdev",
        0.024,
        "arena-preference",
        "arena",
        "coding",
        "aesthetics",
        True,
        1.96,
        "HIGHER",
    ),
    ScoringSource(
        "mercor-apex-agents",
        "mercor-apex-agents:loop-pass-1",
        0.04,
        "professional-work",
        "mercor",
        "tools",
        "professional",
        True,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "vals-finance-agent",
        "vals-finance-agent",
        0.03,
        "professional-work",
        "vals-ai",
        "professional",
        "professional",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "deepswe-v1-1",
        "deepswe-v1-1",
        0.036,
        "software-engineering",
        "datacurve",
        "coding",
        "coding",
        True,
        1.96,
        "HIGHER",
    ),
    ScoringSource(
        "taptap-maker",
        "taptap-maker",
        0.036,
        "game-development",
        "taptap-maker",
        "coding",
        "coding",
        True,
        1.96,
        "HIGHER",
    ),
    ScoringSource(
        "livebench-coding",
        "livebench-coding",
        0.024,
        "rolling-objective",
        "livebench",
        "coding",
        "coding",
        True,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "livebench-reasoning",
        "livebench-reasoning",
        0.042,
        "rolling-objective",
        "livebench",
        "reasoning",
        "reasoning",
        True,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "livebench-writing",
        "livebench-writing",
        0.03,
        "rolling-objective",
        "livebench",
        "writing",
        None,
        True,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "arena-creative-writing",
        "arena-creative-writing",
        0.05,
        "arena-preference",
        "arena",
        "preference",
        "writing",
        True,
        1.96,
        "HIGHER",
    ),
    ScoringSource(
        "arena-vision",
        "arena-vision",
        0.06,
        "arena-preference",
        "arena",
        "vision",
        None,
        True,
        1.96,
        "HIGHER",
    ),
    ScoringSource(
        "tau-banking",
        "tau-banking",
        0.02,
        "customer-service-banking",
        "sierra",
        "tools",
        "professional",
        False,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "epoch-simpleqa",
        "epoch-simpleqa",
        0.04,
        "epoch-simpleqa",
        "epoch-ai",
        "knowledge",
        "knowledge",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "epoch-gpqa",
        "epoch-gpqa",
        0.02,
        "epoch-gpqa",
        "epoch-ai",
        "knowledge",
        "knowledge",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "epoch-frontiermath",
        "epoch-frontiermath",
        0.036,
        "research-mathematics",
        "epoch-ai",
        "reasoning",
        "reasoning",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "epoch-frontiermath-tier4",
        "epoch-frontiermath-tier4",
        0.012,
        "research-mathematics",
        "epoch-ai",
        "reasoning",
        "reasoning",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "epoch-chess",
        "epoch-chess",
        0.018,
        "novel-game-reasoning",
        "epoch-ai",
        "reasoning",
        "reasoning",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "epoch-mystery",
        "epoch-mystery",
        0.012,
        "novel-game-reasoning",
        "epoch-ai",
        "reasoning",
        "reasoning",
        True,
        1,
        "HIGHER",
    ),
    ScoringSource(
        "eq-creative",
        "eq-creative",
        0.036,
        "judged-creative-writing",
        "eq-bench",
        "writing",
        "writing",
        True,
        None,
        "HIGHER",
    ),
    ScoringSource(
        "eq-longform",
        "eq-longform",
        0.024,
        "judged-creative-writing",
        "eq-bench",
        "writing",
        "writing",
        True,
        None,
        "HIGHER",
    ),
)
ANCHORS = (
    "claude-fable-5",
    "gpt-5-6-sol",
    "kimi-k-3",
    "qwen-3-8-max",
    "gpt-5-4",
    "claude-opus-4-8",
    "claude-sonnet-5",
    "grok-4-5",
    "gemini-3-5-flash",
    "glm-5-2",
    "claude-sonnet-4-6",
    "qwen-3-7-max",
    "kimi-k-2-6",
    "deepseek-v-4-pro",
    "qwen-3-6-plus",
    "minimax-m-3",
    "gpt-5-4-mini",
    "grok-4-3",
)


def category_policy(units: int, operators: int) -> Policy:
    return Policy(min(2, units), 1, min(2, operators), 0, 1)
