export const publicItem: HotKeyAPI.PublicItemView = {
  id: "post-1",
  revision: 1,
  title: "公开资讯测试条目",
  original_title: null,
  summary: "固定的来源摘要。",
  summary_origin: "source",
  analysis_state: "not_analyzed",
  backfill: true,
  source: { key: "rss", name: "公开来源", kind: "rss", first_party: true },
  original_url: "https://example.com/post",
  reading_url: "/items/post-1",
  published_at: null,
  discovered_at: "2026-10-06T07:00:00Z",
  timeline_at: "2026-10-06T06:00:00Z",
  category: "paper",
  tags: ["研究"],
  score: null,
  selected: false,
  reason: null,
  event_id: null,
  fact_id: null,
  indexable: false,
};
export const attention: HotKeyAPI.PublicAttentionView = {
  formula_version: "test-v1",
  window_end: "2026-10-06T08:00:00Z",
  last_source_time: "2026-10-06T07:00:00Z",
  heat: 1250,
  previous_heat: 1100,
  eligible: true,
  participant_count: 3,
  editorial_participant_count: 2,
  signal_participant_count: 1,
  comparable_participant_count: 2,
  uncomparable_participant_count: 1,
  comparable_heat: 900,
  comparable_previous_heat: 750,
  trend: "up",
  trend_pct: 20,
  complete: false,
  badges: ["surge", "rising"],
};
export const publicStory: HotKeyAPI.PublicStoryView = {
  id: "story-1",
  revision: 1,
  title: "公开事件测试条目",
  summary: "固定的公开事件摘要。",
  latest_progress: null,
  phase: "active",
  first_seen_at: "2026-10-05T00:00:00Z",
  heat: 1250,
  attention,
  reports: [publicItem, { ...publicItem, id: "post-2" }],
};
